# Generated by Django 3.2.3 on 2024-02-04 16:24

import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20240129_1640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodgramuser',
            options={'ordering': ('-pub_date',), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ('-subscriber', 'subscribed_to'), 'verbose_name': 'Subscription', 'verbose_name_plural': 'Subscriptions'},
        ),
        migrations.AddField(
            model_name='foodgramuser',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foodgramuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
